name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gcc-multilib g++-multilib

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --config .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: funkify-linux-x86_64
          path: ./dist/golang-cross-build_linux_amd64_v1/golang-cross-build

  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --config .goreleaser-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: find . -type f

      - uses: actions/upload-artifact@v3
        with:
          name: funkify-darwin-x86_64
          path: ./dist/golang-cross-build_darwin_amd64/golang-cross-build          

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gcc-mingw-w64-x86-64

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --config .goreleaser-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: funkify-windows-x86_64.exe
          path: ./dist/golang-cross-build_windows_amd64_v1/golang-cross-build.exe

  publish-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir -p ./funkify-build
          mkdir -p ./funkify-build

      - uses: actions/download-artifact@v3
        with:
          path: ./funkify-build

      - run: |
          mv ./funkify-build/funkify-linux-x86_64/golang-cross-build ./funkify-build/linux
          rm -rf ./funkify-build/funkify-linux-x86_64
          mv ./funkify-build/linux ./funkify-build/funkify-linux-x64_64

          mv ./funkify-build/funkify-darwin-x86_64/golang-cross-build ./funkify-build/darwin
          rm -rf ./funkify-build/funkify-darwin-x86_64
          mv ./funkify-build/darwin ./funkify-build/funkify-darwin-x64_64          

          mv ./funkify-build/funkify-windows-x86_64.exe/golang-cross-build.exe ./funkify-build/windows.exe
          rm -rf ./funkify-build/funkify-windows-x86_64.exe
          mv ./funkify-build/windows.exe ./funkify-build/funkify-windows-x86_64.exe

          xz ./funkify-build/*
          shasum ./funkify-build/* > ./funkify-build/checksums.txt

      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release --config .goreleaser-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}